# Generated by Django 5.1 on 2024-08-20 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandiseStoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_category/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoryCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseStoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=1, null=True)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('advertisement_image', models.ImageField(blank=True, null=True, upload_to='product/advertisement/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productCategory', to='store.merchandisestorecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('is_love', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('leagues_for', models.ManyToManyField(blank=True, to='team.leagues')),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('current_price', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total_product', models.PositiveIntegerField(blank=True, null=True)),
                ('available_product', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificProduct', to='store.merchandisestoreproduct')),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='store_product/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='store.merchandisestoreproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('percentage', models.IntegerField(default=0, help_text='This Input Count As A Discount Percentage')),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(blank=True, to='store.merchandisestoreproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('default_address', models.BooleanField(default=False)),
                ('complete_address', models.TextField(blank=True, help_text='street, city, state, country, PIN-postal_code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMerchandiseStoreProductBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('secret_key', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('cart_idd', models.CharField(blank=True, max_length=250, null=True)),
                ('price_per_product', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveBigIntegerField()),
                ('status', models.CharField(blank=True, choices=[('CART', 'CART'), ('BuyNow', 'BUY NOW'), ('ORDER PLACED', 'ORDER PLACED'), ('CANCEL', 'CANCEL'), ('DELIVERED', 'DELIVERED')], max_length=250, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_address', models.TextField(blank=True, help_text='street, city, state, country, PIN-postal_code', null=True)),
                ('delivered_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productBuyby', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='store.merchandisestoreproduct')),
                ('delivery_address_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productdeliveryaddress')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rate between 1 and 5.')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratedProduct', to='store.merchandisestoreproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productRatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchLogs', to='store.merchandisestoreproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecificationHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_key', models.CharField(blank=True, max_length=255, null=True)),
                ('highlight_des', models.TextField(blank=True, null=True)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificHighlight', to='store.merchandiseproductspecification')),
            ],
        ),
        migrations.CreateModel(
            name='RatingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='store_product/product_rating_images')),
                ('product_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingImages', to='store.productrating')),
            ],
        ),
    ]
