# Generated by Django 5.1 on 2025-07-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_merchandisestoreproduct_store_name_merchandisestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandisestoreproduct',
            name='has_single_spec',
            field=models.BooleanField(default=False, help_text='Check if this product requires only one specification'),
        ),
    ]
