# Generated by Django 5.1 on 2025-07-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_merchandisestoreproduct_has_single_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdeliveryaddress',
            name='latitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='productdeliveryaddress',
            name='longitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customermerchandisestoreproductbuy',
            name='status',
            field=models.CharField(blank=True, choices=[('CART', 'CART'), ('BuyNow', 'BUY NOW'), ('ORDER PLACED', 'ORDER PLACED'), ('SHIPPED', 'SHIPPED'), ('CANCEL', 'CANCEL'), ('DELIVERED', 'DELIVERED')], max_length=250, null=True),
        ),
    ]
