# Generated by Django 5.1 on 2025-07-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productdeliveryaddress_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiseproductspecification',
            name='color',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
