# Generated by Django 5.1 on 2025-07-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_merchandiseproductspecification_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermerchandisestoreproductbuy',
            name='color',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
