# Generated by Django 5.1 on 2025-07-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customermerchandisestoreproductbuy_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandisestoreproduct',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
