from django.urls import path
from . import views
from django.shortcuts import render

app_name = "user_side"

urlpatterns = [
    path('', views.user_login, name="user_login"),
    path('logout_view_user', views.logout_view_user, name="logout_view_user"),
    path('signup/', views.user_signup, name="user_signup"),
    path('api/nearby-pickleball/', views.nearby_pickleball, name='nearby_pickleball'),
    path('api/proxy-google-places/', views.proxy_google_places, name='proxy_google_places'),
    path('index/', views.index, name="user_index"),
    path('go_app_to_web/<str:user_uuid>/', views.go_app_to_web, name="go_app_to_web"),
    path('user_list/', views.user_list, name='user_list'),
    path('player_profile/<int:pk>/', views.player_profile, name='player_profile'),
    path('follow_player/<int:pk>/', views.follow_player, name='follow_player'),
    path('profile/', views.profile, name="user_profile"),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('find_team_list/', views.find_team_list, name="find_team_list"),
    path('find_my_team_list/', views.find_my_team_list, name="find_my_team_list"),
    path('create_team_user_side/', views.create_team_user_side, name='create_team_user_side'),
    path('search_players_user_side/', views.search_players_user_side, name='search_players_user_side'),
    path('team_view_user/<int:team_id>/', views.team_view_user, name="team_view_user"),
    path('add_event/', views.add_event, name="add_event"),
    path('event/', views.event, name="event_user"),
    path('event_view/<int:event_id>/', views.event_view, name="event_view"),
    path('get-cancellation-policy/', views.get_cancellation_policy, name='get_cancellation_policy'),
    path('remove-team-from-league/', views.remove_team_from_league, name='remove_team_from_league'),
    path('delete_event/<int:event_id>/', views.event_delete, name="delete_event"),
    path('join_team_event/<int:event_id>/', views.join_team_event, name="join_team_event"),
    path('event_update_score/<int:event_id>/', views.event_update_score, name="event_update_score"),
    path('event/match/<int:match_id>/update_scores/', views.update_match_scores, name='update_match_scores'),
    path('event/match/<int:match_id>/get_scores/', views.get_match_scores, name='get_match_scores'),
    path('event/match/<int:match_id>/update_tournament/', views.update_tournament_settings, name='update_tournament_settings'),
    path('openplay_list/', views.openplay_list, name="openplay_list"),
    path('create_openplay/', views.create_openplay, name="create_openplay"),
    path('search-users/', views.search_users, name="search-users"),
    path('invitation_list/', views.invitation_list, name="invitation_list"),
    path("confirm-payment/", views.confirm_payment, name="confirm_payment"),
    path("initiate-stripe-payment/", views.initiate_stripe_payment, name="initiate_stripe_payment"),
    path('stripe_success/<int:event_id>/<str:team_ids>/<str:checkout_session_id>/', views.stripe_success, name='stripe_success'),
    path('match_history/', views.match_history, name="match_history_user"),
    path('user_wallet/', views.user_wallet_foruser, name="user_wallet"),
    path("add-fund/", views.add_fund, name="add_fund"),
    path("create-checkout-session/", views.create_checkout_session, name="create_checkout_session"),
    path('payment-success/', views.payment_success, name="payment-success"),
    path('payment-failed/', views.payment_failed, name="payment-failed"),
    path("stripe-webhook/", views.stripe_webhook, name="stripe_webhook"),
    path('edit_team/<int:team_id>/', views.edit_team, name="edit_team"),
    path('start_tournament/<int:event_id>/', views.start_tournament, name='start_tournament'),
    path('edit_event/<int:event_id>/', views.edit_event, name='edit_event'),
    path('search_teams/', views.search_teams, name='search_teams'),
    path('search_organizers/', views.search_organizers, name='search_organizers'),
    path('search_players/', views.search_players, name='search_players'),
    path('my_ad_list/', views.my_ad_list, name="my_ad_list"),
    path('add_advertisement/', views.create_advertisement, name="add_advertisement"),
    path('get_ad_rate/', views.get_ad_rate, name='get_ad_rate'),
    path('confirm_payment_for_advertisement/', views.confirm_payment_for_advertisement, name='confirm_payment_for_advertisement'),
    path('initiate_stripe_payment_for_advertisement/', views.initiate_stripe_payment_for_advertisement, name='initiate_stripe_payment_for_advertisement'),
    path('stripe_success_for_advertisement/<str:my_data>/<str:checkout_session_id>/', views.stripe_success_for_advertisement, name='stripe_success_for_advertisement'),
    path('all_club_list/', views.all_club_list, name='all_club_list'),
    path('fetch_google_clubs/', views.fetch_google_clubs, name='fetch_google_clubs'),
    path('club_view/<int:pk>/', views.club_view, name='club_view'),
    path('my_club_list/', views.my_club_list, name='my_club_list'),
    path('add_my_club', views.add_my_club, name='add_my_club'),
    path('add_my_club_package/', views.add_my_club_package, name="add_my_club_package"),
    path("add-review/", views.add_review, name="add_review"),
    path("load-more-reviews/<int:club_id>/", views.load_more_reviews, name="load_more_reviews"),
    path('get_wallet_balance_and_amount_to_pay/', views.get_wallet_balance_and_amount_to_pay, name='get_wallet_balance_and_amount_to_pay'),
    path('confirm_payment_for_book_club/', views.confirm_payment_for_book_club, name='confirm_payment_for_book_club'),
    path('initiate_stripe_payment_for_booking_club/', views.initiate_stripe_payment_for_booking_club, name='initiate_stripe_payment_for_booking_club'),
    path('stripe_success_for_booking_club/<str:stripe_fees>/<str:my_data>/<str:checkout_session_id>/', views.stripe_success_for_booking_club, name='stripe_success_for_booking_club'),
    path('booking_list/<int:club_id>/', views.booking_list, name='booking_list'),
    path('joined_list/<int:club_id>/', views.joined_list, name='joined_list'),
    path('confirm_payment_for_join_club/', views.confirm_payment_for_join_club, name='confirm_payment_for_join_club'),
    path('initiate_stripe_payment_for_join_club/', views.initiate_stripe_payment_for_join_club, name='initiate_stripe_payment_for_join_club'),
    path('stripe_success_for_join_club/<str:stripe_fees>/<str:my_data>/<str:checkout_session_id>/', views.stripe_success_for_join_club, name='stripe_success_for_join_club'),
    path('all_court_list/', views.all_court_list, name='all_court_list'),
    path('my_court_list/', views.my_court_list, name='my_court_list'),
    path('fetch_pickleball_courts/', views.fetch_pickleball_courts, name='fetch_pickleball_courts'),
    path('court_view/<int:pk>', views.court_view, name='court_view'),
    path('add_my_court/', views.add_my_court, name='add_my_court'),
    path('read_notifications/', views.read_notifications, name='read_notifications'),
    path('socail_feed_list/', views.social_feed, name='socail_feed_list'),
    path('post/add/', views.add_post, name='add_post'),
    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('post/<int:post_id>/', views.view_post, name='view_post'),

    #store urls
    path('create-store/', views.create_store, name='create_store_user_side'),
    path('my-store/', views.my_store, name='my_store_user_side'),
    path('product-list/', views.product_list, name="product_list_user_side"),
    path('cart-count/', views.cart_count, name='cart_count'),
    path('pending-order-count/', views.pending_received_order_count, name='pending_received_order_count'),
    path('add-product/', views.add_store_product, name='add_store_product_user_side'),
    path('product_view/<int:product_id>/', views.store_product_view, name='product_view'),
    path('ajax/get-specification/', views.get_specification_data, name='get_specification_data'),
    path('load-single-variation-edit/<int:product_id>/', views.load_single_variation_edit, name='load_single_variation_edit'),
    path('load-multiple-variation-edit/<int:product_id>/', views.load_multiple_variation_edit, name='load_multiple_variation_edit'),
    path('edit_store_product/<int:product_id>/', views.edit_store_product, name='edit_store_product'),
    path('my-orders/', views.my_orders, name='my_order_user_side'),
    
    path('my_placed_orders/', views.my_placed_orders, name='my_placed_orders_user_side'),
    path('change-order-status/<int:order_id>/', views.change_order_status, name='change_order_status_user_side'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart_user_side'),
    path('add-to-wishlist/', views.add_to_wishlist, name='add_to_wishlist_user_side'),
    path('buy-now/', views.buy_now, name='buy_now_user_side'),
    path('checkout_summary/<int:order_id>/', views.checkout_summary, name='checkout_summary_user_side'),
    path('wishlist/', views.wishlist, name='wishlist_user_side'),
    path('cart/', views.cart, name="cart_user_side"),
    path('update_cart', views.update_cart, name='update_cart_user_side'),
    path('cart-remove-item/', views.remove_cart_item, name='remove_cart_item_user_side'),
    path('apply_coupon/', views.apply_coupon, name='apply_coupon_user_side'),

    path('select-address/', views.select_address, name='select_address_user_side'),
    path('add-address-ajax/', views.add_address_ajax, name='add_address_ajax_user_side'),

    path('cart_payment_gateway/', views.cart_payment_gateway, name='cart_payment_gateway_user_side'),
    path('create_cart_checkout_session/', views.create_cart_checkout_session, name='create_cart_checkout_session_user_side'),
    path('cart_payment_success/', views.cart_payment_success, name='cart_payment_success_user_side'),
    path('cart_payment_cancel/', views.cart_payment_cancel, name='cart_payment_cancel_user_side'),
    path('cart/webhook/', views.stripe_cart_webhook, name='stripe_cart_webhook_user_side'),
    path('buy_now_payment_gateway/', views.buy_now_payment_gateway, name='buy_now_payment_gateway_user_side'),
    path('select_address_buy_now/', views.select_address_buy_now, name='select_address_buy_now_user_side'),
    path('create_buy_now_checkout_session/', views.create_buy_now_checkout_session, name='create_buy_now_checkout_session_user_side'),
    path('buy_now_payment_success/', views.buy_now_payment_success, name='buy_now_payment_success_user_side'),
    path('buy_now_payment_cancel/', views.buy_now_payment_cancel, name='buy_now_payment_cancel_user_side'),
    path('add_review', views.add_review, name="add_review_user_side"),
    

    path('accept_openplay_invitation/<int:pk>/', views.accept_openplay_invitation, name='accept_openplay_invitation'),
    path('decline_openplay_invitation/<int:pk>/', views.decline_openplay_invitation, name='decline_openplay_invitation'),


    ##app to web
    path('app_to_web/<str:user_uuid>/', views.app_to_subscription_page, name='app_to_web'),
    path('subcription_plan/', views.subcription_plan, name='subcription_plan'),

    #adveticement
    path('advertisements/', views.get_advertisements, name='get_advertisements'),

    #unauthenticated pages
    path('unauthenticated_base/<int:pk>/', views.unauthenticated_base_view, name='unauthenticated_base'),
    path('unauthenticated_share/<int:pk>/', views.unauthenticated_feed_view, name='unauthenticated_share')



]

