# Generated by Django 5.1 on 2025-01-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_full_location_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_location',
            new_name='current_location',
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
