# Generated by Django 5.1 on 2025-02-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_subscriptionplan_subscription_payment_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
