# Generated by Django 5.1 on 2025-02-21 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_adminwallet_adminwallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='wallet',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='admin_cost',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='getway_charge',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reciver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_reciver_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reciver_cost',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_sender_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_for',
            field=models.CharField(choices=[('Subscription', 'Subscription'), ('AddMoney', 'AddMoney'), ('TeamRegistration', 'TeamRegistration'), ('Advertisement', 'Advertisement'), ('Store', 'Store')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
