# Generated by Django 5.1 on 2025-02-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_wallettransaction_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_for',
            field=models.CharField(choices=[('Subscription', 'Subscription'), ('AddMoney', 'AddMoney'), ('TeamRegistration', 'TeamRegistration'), ('Advertisement', 'Advertisement'), ('Store', 'Store'), ('Withdraw', 'Withdraw')], max_length=20),
        ),
    ]
