# Generated by Django 5.1 on 2025-02-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_wallettransaction_transaction_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
