# Generated by Django 5.1 on 2025-03-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_withdrawalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
