# Generated by Django 5.1 on 2025-03-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_subscriptionplan_subscription_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MatchingPlayers',
        ),
    ]
