# Generated by Django 5.1 on 2025-03-18 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_availability_user_dob_delete_matchingplayers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_rank', models.CharField(blank=True, max_length=5, null=True)),
                ('to_rank', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('search_availability', models.JSONField(blank=True, default=dict, null=True)),
                ('from_age', models.IntegerField(blank=True, null=True)),
                ('to_age', models.IntegerField(blank=True, null=True)),
                ('redious', models.IntegerField(blank=True, null=True)),
                ('team_type', models.CharField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double'), ('Co-ed', 'Co-ed')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
