# Generated by Django 5.1 on 2025-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_matchingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
