# Generated by Django 5.1 on 2025-03-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_is_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
