# Generated by Django 5.1 on 2025-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_storecallid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('discount', models.CharField(max_length=6)),
                ('codefor', models.CharField(choices=[('team_registration', 'Team Registration'), ('advertisement', 'Advertisement'), ('add_fund', 'Add Fund'), ('club_booking', 'Club Booking')], max_length=20)),
            ],
        ),
    ]
