# Generated by Django 5.1 on 2025-04-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecallid',
            name='role',
            field=models.CharField(choices=[('viewer', 'viewer'), ('admin', 'admin')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
