# Generated by Django 5.1 on 2025-04-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_storecallid_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecallid',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
