# Generated by Django 5.1 on 2025-04-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_storecallid_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TransactionFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField(default=dict)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.wallettransaction')),
            ],
        ),
    ]
