# Generated by Django 5.1 on 2025-04-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_subscriptionplan_product_id_transactionfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_for',
            field=models.CharField(choices=[('Subscription', 'Subscription'), ('AddMoney', 'AddMoney'), ('TeamRegistration', 'TeamRegistration'), ('Advertisement', 'Advertisement'), ('Store', 'Store'), ('BookClub', 'BookClub'), ('JoinClub', 'JoinClub'), ('Withdraw', 'Withdraw')], max_length=20),
        ),
    ]
