# Generated by Django 5.1 on 2025-06-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_for',
            field=models.CharField(choices=[('Subscription', 'Subscription'), ('AddMoney', 'AddMoney'), ('TeamRegistration', 'TeamRegistration'), ('Advertisement', 'Advertisement'), ('Plan', 'Plan'), ('Store', 'Store'), ('BookClub', 'BookClub'), ('JoinClub', 'JoinClub'), ('Withdraw', 'Withdraw')], max_length=20),
        ),
    ]
