# Generated by Django 5.1 on 2025-03-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpackage',
            name='valid_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubpackage',
            name='valid_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
