# Generated by Django 5.1 on 2024-11-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='registered_team',
            field=models.ManyToManyField(blank=True, to='team.team'),
        ),
    ]
