# Generated by Django 5.1 on 2024-12-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_leagues_registered_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
