# Generated by Django 5.1 on 2025-01-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_player_player_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(blank=True, to='team.team'),
        ),
    ]
