# Generated by Django 5.1 on 2025-02-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='policy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='latitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='longitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='LeaguesCancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('within_day', models.IntegerField()),
                ('refund_percentage', models.FloatField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.leagues')),
            ],
        ),
    ]
