# Generated by Django 5.1 on 2025-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_player_follower_player_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
