# Generated by Django 5.1 on 2025-05-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_openplayinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='play_type',
            field=models.CharField(blank=True, choices=[('Group Stage', 'Group Stage'), ('Round Robin', 'Round Robin'), ('Single Elimination', 'Single Elimination'), ('Individual Match Play', 'Individual Match Play'), ('Round Robin Compete to Final', 'Round Robin Compete to Final'), ('Robin Randomizer', 'Robin Randomizer')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leaguesplaytype',
            name='type_name',
            field=models.CharField(choices=[('Group Stage', 'Group Stage'), ('Round Robin', 'Round Robin'), ('Single Elimination', 'Single Elimination'), ('Individual Match Play', 'Individual Match Play'), ('Round Robin Compete to Final', 'Round Robin Compete to Final'), ('Robin Randomizer', 'Robin Randomizer')], max_length=255),
        ),
    ]
