# Generated by Django 5.1 on 2025-02-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleitcollection', '0004_advertisementdurationrate_advertisement_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='admin_approve_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=25),
        ),
    ]
