# Generated by Django 5.1 on 2025-03-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleitcollection', '0006_advertisement_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='approved_by_admin',
            field=models.BooleanField(default=True),
        ),
    ]
