# Generated by Django 5.1 on 2025-06-04 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleitcollection', '0007_alter_advertisement_approved_by_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorspost',
            name='number_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ambassadorspost',
            name='number_like',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pickleitcollection.postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_comment', to='pickleitcollection.ambassadorspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenting_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
