# Generated by Django 5.1 on 2025-06-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleitcollection', '0008_ambassadorspost_number_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number_of_use', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ambassadorspost',
            name='tags',
            field=models.JSONField(default={}),
        ),
    ]
