# Generated by Django 5.1 on 2025-07-18 08:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleitcollection', '0009_tags_ambassadorspost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
