# Generated by Django 5.1 on 2025-07-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleitcollection', '0010_alter_paymentdetails_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='var_chargeamount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
