# Generated by Django 5.1 on 2025-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleitcollection', '0011_alter_paymentdetails_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='var_chargeamount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
