# Generated by Django 5.1 on 2025-07-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleitcollection', '0012_alter_paymentdetails_payment_amount_and_more'),
        ('store', '0006_customermerchandisestoreproductbuy_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_for_product',
            field=models.ManyToManyField(blank=True, to='store.customermerchandisestoreproductbuy'),
        ),
    ]
