# Generated by Django 5.1 on 2025-07-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleitcollection', '0013_paymentdetails_payment_for_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorspost',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
